# Generated by Django 4.2.4 on 2023-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DF', 'Waiting'), ('PB', 'Done')], default='DF', max_length=2),
        ),
    ]
