# Generated by Django 4.2.4 on 2023-08-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('WT', 'Waiting'), ('DN', 'Done')], default='WT', max_length=2),
        ),
    ]
